### ISSUE TITLE
Documentations are not reachable due to SourceForge

### ISSUE THREAD

**Issue by daf182** [DozerMapper/dozer#256]
Can't read the docs due to:
"The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service."

**Comment by piis3** [comment]
Much worse, the dozer xml config schema is also unavailable:
http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd

The version of dozer that happened to be in use in one of my applications, 5.3.2, actually tries to fetch this in order to validate the config file against the schema, and causes all dozer map calls to fail. Luckily I was able to stop using the config file by using my own dozer singleton instead of the provided DozerBeanMapperSingletonWrapper which avoided the problem.

**Comment by jetrii** [comment]
It appears to be back online.

**Comment by lauriharpf** [comment]
Closing, since sourceforge.net is back online. Thanks for the reports, though!
