### ISSUE TITLE
No getter/setter dozer map failed

### ISSUE THREAD

**Issue by zhugw** [DozerMapper/dozer#274]
```
 @Test
  public void test_map_no_setter_and_getter_object() {
    Foo f = new Foo();
    f.id = 1;
    f.name = "foo";

    Foo dest = BeanMapper.map(f, Foo.class);
    Assert.assertEquals(f.name, dest.name);
    Assert.assertEquals(f.id, dest.id);
  }

  public static class Foo {
    public int id;
    public String name;
  }
```

Check result:
`java.lang.AssertionError: expected:<foo> but was:<null>`

**Comment by g00glen00b** [comment]
Isn't that expected behaviour? Dozer maps by accessors/mutators by default. If you didn't add the property ID explicitely to the field mappings, then it will throw no error but it won't throw either.

If you want to map fields without using accessors/mutators, you can use `is-accessible="true"` and if you're using the Java API you can use `field("id").accessible()`.

**Comment by zhugw** [comment]
How ? need to modify dozer source code?

**Comment by g00glen00b** [comment]
No, you can configure it: http://dozer.sourceforge.net/documentation/custommethods.html

With the Java API it's also possible:

```
mapping(Foo.class, Foo.class)
    .fields(field("id").accessible(), field("id").accessible())
    .fields(field("name").accessible(), field("name").accessible());
```

**Comment by zhugw** [comment]
yeah, got it. I'll try it . Thanks!

**Comment by garethahealy** [comment]
Solution provided.
