### ISSUE TITLE
@Mapping("user.id") problem

### ISSUE THREAD

**Issue by ghost** [DozerMapper/dozer#30]
I using Dozer in my project with xml mapping but i want to  used annotation and remove xml file 
this example show bug in annotation mapping 
after mapping to destination bean ,type of variable is changed from Integer to String 

for example

```
public class User {
       private Integer id; 
}

public class UserBean {
       @Mapping("user.id")
       private Integer userId; 
}
```
```
userBean.getUserId()//is not Integer it is String
```

I think one of  the dozer disadvantage  is in annotation
annotation is very simple and changeable

**Comment by peruzzo** [comment]
+1

**Comment by rweng** [comment]
+1

**Comment by azizkhani** [comment]
+100 plz add this to next release

**Comment by garethahealy** [comment]
@azizkhani can you please provide more info. I don't understand your original comment.

**Comment by azizkhani** [comment]
@garethahealy when map object using annotation ,type of property that create in  proxy object is not integer

**Comment by garethahealy** [comment]
@azizkhani ; can you please create a github repo, with a unit test showing the behaviour / failure please. It will make it easier to investigate.

**Comment by azizkhani** [comment]
@garethahealy   i create project that show that bug  https://github.com/azizkhani/dozer/tree/master/test

**Comment by azizkhani** [comment]
@garethahealy are u check bug?

**Comment by azizkhani** [comment]
+100

**Comment by garethahealy** [comment]
After some quick debugging, it seems the below:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/propertydescriptor/FieldPropertyDescriptor.java#L56

Is returning id as type Object, due to generics, which then cascades down to:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L382

Which then causes the primitiveconverter, to convert to a string:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L492

As a quick change (if its possible), changing to: BaseEntity<Integer> stops the error.

Due to Java generics type erasure, the code cant resolve the type.

We'd need to use something like classmate to get the correct type back, which isn't a small change.

**Comment by garethahealy** [comment]
CC @orange-buffalo @buzdin

**Comment by azizkhani** [comment]
+100

**Comment by azizkhani** [comment]
why dozer team dose not solve this bug? 
I had to use xml instead of annotation because this bug dose not resolve yet?
please

**Comment by garethahealy** [comment]
@azizkhani ; the "dozer team" is currently me. i am not paid by anyone to work on this project, i do it in my own spare time. why dont you help, and work on the issue? like i said in the comment. this is not a simple change.
