### ISSUE TITLE
Override Field Mapping In Subclass

### ISSUE THREAD

**Issue by tausiffarooqi** [DozerMapper/dozer#300]
Is there no way to override a field mapping in a sub class? I have the following mapping:

&lt;mapping type=&quot;one-way&quot;&gt;
	&lt;class-a&gt;ClassA&lt;/class-a&gt;
	&lt;class-b&gt;ClassB&lt;/class-b&gt;
	&lt;field&gt;
		&lt;a&gt;fieldA1&lt;/a&gt;
		&lt;b&gt;fieldB1&lt;/b&gt;
	&lt;/field&gt;
	&lt;field custom-converter=&quot;CustomConverter1&quot;&gt;
		&lt;a&gt;this&lt;/a&gt;
		&lt;b&gt;fieldB2&lt;/b&gt;
	&lt;/field&gt;
&lt;/mapping&gt;

&lt;mapping type=&quot;one-way&quot;&gt;
	&lt;class-a&gt;ClassA&lt;/class-a&gt;
	&lt;class-b&gt;SubClassB&lt;/class-b&gt;
	&lt;field&gt;
		&lt;a&gt;fieldA1&lt;/a&gt;
		&lt;b&gt;fieldSubB1&lt;/b&gt;
	&lt;/field&gt;
	&lt;field custom-converter=&quot;CustomConverter2&quot;&gt;
		&lt;a&gt;this&lt;/a&gt;
		&lt;b&gt;fieldB2&lt;/b&gt;
	&lt;/field&gt;
&lt;/mapping&gt;

When I execute the mapping it completely ignores the mapping of "fieldB2" in the mapping of ClassA to SubClassB and "CustomConverter2" is never invoked. Is there a way to have "CustomConverter2" invoked for fieldB2?

**Comment by garethahealy** [comment]
@tausiffarooqi ; can you provide a github repo providing a working unit test. Make its easy to understand the problem / requirement.

**Comment by vguna** [comment]
I encountered the same behavior. For me, it's mainly about excluding fields from classA in a mapping for SubClassB. That does not seem possible at the moment. I mean, _all_ mappings for superclass attributes in a subclass mapping are ignored. See:

https://sourceforge.net/p/dozer/bugs/269/

Which is referenced by dmitry in

https://sourceforge.net/p/dozer/discussion/452530/thread/72589789/

A while back I took a look at the code, trying to understand, why subclass mappings for superclass fields aren't working. It showed, that mappings are done in the order from superclass to subclass mappings. If a mapping for a field of the superclass has already been done, a mapping for the same subclass field isn't evaluated anymore. So it's some kind of caching - which would make sense as long as there's no "override" in the sub class mapping. But especially the override mappings (for me: mainly excludes) are the ones of interest.

I considered switching to Orika or similar due to this. But as Dozer seems to be reactivated from hibernate thanks to you guys, maybe I don't have to do it in the end :).

**Comment by garethahealy** [comment]
@vguna ; can you please retest with latest - 6.0.0
- https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v5-to-v6.adoc

**Comment by vguna** [comment]
I tried 6.0.0 with an isolated test. Sadly without any effect :,-(. Please find attached a maven project with a testng test that shows the problem.

[dozer-test.zip](https://github.com/DozerMapper/dozer/files/1117496/dozer-test.zip)

Maybe that helps.

**Comment by garethahealy** [comment]
@vguna ; instead of providing a zip, can you create a github repo with the test and provide the link. Its much easier to clone/look at.

**Comment by vguna** [comment]
Fair enough. Provided the testcase here: https://github.com/vguna/dozer-tests/blob/master/src/test/java/test/SubclassMappingOverrideSuperclassMappingTest.java

**Comment by garethahealy** [comment]
Related to:
- https://github.com/DozerMapper/dozer/issues/451
