### ISSUE TITLE
Feature parity between xml vs api vs annotations 

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#415]
Currently have 3 methods of configuring dozer:
- xml
- api
- annotations

Validate that all 3 are equal in terms of features.

**Comment by buzdin** [comment]
Should they be equal? I don't think that annotations can support all variations for example. Because API would become quite messy. I would think in the direction of refactoring Dozer core API in order to support more convenient mappings approaches. Lambda based and Kotlin-based for example. XML API is a pain and no one wants to use it. Annotations are not usable in all cases, because you have to change at least one side of beans being converted.

I think there is a need for Dozer 2018 API out there.

**Comment by sriki77** [comment]
The `@Mapping` annotation can be enhanced to support the `<fields>` tag properties like key etc.  I mean configuring the contents of `DozerField` class.

**Comment by eonezhang** [comment]
how about add a convert support for `Mapping` annotation.
such as 
```
@Mapping(converter=StringToUUIDConverter.class, value="id")
private String uuid;
```

class StringToUUIDConverter implements Converter {
   @Override
   Object convert(Object value, Object source, Object target){}
}
