### ISSUE TITLE
Class based one-way mapping not working as expected

### ISSUE THREAD

**Issue by vguna** [DozerMapper/dozer#451]
## Whats your runtime?
* Dozer version: 6.0.0
* OS version: Win 7
* JDK version: JDK8
  
## Whats the problem?
Providing a source class with multiple destination classes doesn't seem to respect one-way mappings properly when one of the one-way destination classes is mapped back to source.

Executing https://github.com/vguna/dozer-tests/blob/master/src/test/java/test/OneWayClassMappingTest.java shows the problem.
 
### Observed Results:
The attribute `oneWay` is mapped to entity, although it shouldn't, based on the mappings.
  
### Expected Results:
The attribute `oneWay` should not be mapped to entity.

## Link to GitHub repo with Unit test
https://github.com/vguna/dozer-tests/blob/master/src/test/java/test/OneWayClassMappingTest.java

**Comment by garethahealy** [comment]
@vguna ; have had a look into this and will raise a PR that will fix the 2 issues.

1. One-way issue is because your example hits "classMapBuilder.createDefaultClassMap" for the other relationship. See:

https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L1148-L1161

2. Subclass issue is because the excludes are not passed down the classmap chain when looking at super types. See:

https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L1069

Should be able to merge the PR in the next day or two.

**Comment by vguna** [comment]
This is good news :)! Thanks for looking into this!
