### ISSUE TITLE
module structure

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#527]
Currently we have 2 integrations / extra modules:

- spring
- proto

There is a PR open to add springboot support as well, and its been suggested by @orange-buffalo to move the spring structure as per:

> dozer
> |- dozer-spring-support (currently does not exist, aggregate module)
> |   |- dozer-spring (existing module from spring folder)
> |   |- dozer-spring-boot-starter (newly introduced module)
> |   |- dozer-spring-boot-autoconfigure (newly introduced module)
> |- ... 

I'd also like to suggest moving proto under a top level aggregate, something like "dozer-integrations"

i.e.:

> dozer
> |- dozer-integrations
> |   |- dozer-proto3 (existing module from proto folder **but to be renamed to proto3**)
> |   |- dozer-spring-support (currently does not exist, aggregate module)
> |   |   |- dozer-spring4 (existing module from spring folder **but to be renamed to spring4**)
> |   |   |- dozer-spring-boot-starter (newly introduced module)
> |   |   |- dozer-spring-boot-autoconfigure (newly introduced module)
> |- ...

**Comment by garethahealy** [comment]
CC @orange-buffalo @jbq @vadeg

**Comment by vadeg** [comment]
@garethahealy please correct me if I am wrong: this PR should be done before #526?

**Comment by garethahealy** [comment]
@vadeg ; no, it can be done afterwards.

**Comment by vadeg** [comment]
@buzdin @garethahealy could you please clarify why all `XML` schemas (main dozer schema and spring schema) are located in a separate module `dozer-schema`? I do not see any benefits of it. It looks like an overkill. Dozer has a `spring` module which encapsulates all spring-related features. I think `dozer-spring` schema should be also in this module because it is spring-related.
For `dozer-mapping` schema `dozer-core` is a good candidate. 
I do not see any use-case where schema can be used separately. Maybe you can provide such use-case?
Is it somehow related to OSGi? From my experience I do not remember such requirements for OSGi environment.

**Comment by garethahealy** [comment]
@vadeg ; its removed with this PR
- https://github.com/DozerMapper/dozer/pull/532

**Comment by vadeg** [comment]
@garethahealy thank you.
