### ISSUE TITLE
OSGi tests fail randomly

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#541]
Locally and on travis, see the below every now and again:

> [ERROR] com.github.dozermapper.osgitests.karaf.DozerCoreKaraf2MinimalDependenciesOsgiContainerTest  Time elapsed: 6.354 s  <<< ERROR!
> java.lang.RuntimeException: waitForState
> Caused by: java.rmi.UnmarshalException: 
> Error unmarshaling return header; nested exception is: 
> 	java.io.EOFException
> Caused by: java.io.EOFException
> 
> [ERROR] com.github.dozermapper.osgitests.karaf.DozerCoreKaraf2MinimalDependenciesOsgiContainerTest  Time elapsed: 6.388 s  <<< ERROR!
> java.lang.RuntimeException: Container never came up
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)

**Comment by garethahealy** [comment]
@orange-buffalo ; has any of your guys seen this before? if i run the tests it works eventually, but that might take quite a few times (maybe 4 or 5)

**Comment by orange-buffalo** [comment]
Unfortunately, no. When we created the tests, maven executions were running fine.

**Comment by vadeg** [comment]
I see this every time. It fails randomly for sure and it is causes only `karaf-2`. `karaf-4` is working fine. 
I did some investigations and figured out that problem is in RMI connection between test container and `karaf` container. In short, if there are more than two tests for `karaf` running then they are starting randomly failing because test container can not get response via RMI from karaf container. Connection timeout happens before. I think this is because of containers startup/shutdown intersection. When one test is finished it removes container. Container need some time to free resources. While it is shutting down another container is starting up. It seems that new test container waiting data from old container somehow rather than getting data from new container.

I would remove `karaf-2` support from dozer completely. According to [this doc](http://karaf.apache.org/download.html) it is not developed and not maintained for the last two years. The last [`karaf-2` release](https://github.com/apache/karaf/commit/d1d130d5d929451170b3d844bf0ae32dc4ba203c) was 21/01/2016.

**Comment by garethahealy** [comment]
@vadeg ; karaf-2 tests are supported as i know quite a few people who deploy dozer onto karaf-2. I expect to drop the tests sometime either later this year / early 2019.

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/issues/565
