### ISSUE TITLE
Type safe generic converter 

### ISSUE THREAD

**Issue by wind57** [DozerMapper/dozer#740]
This is more of a question rather than a bug. Suppose that the source is a `String` and destination is, well, not yet known. Meaning that this String represents some json, and we use Gson to convert this string to some class. There are multiple cases where we do that. For example, one certain String can represent DTO_A, another String represents DTO_B. The actual code for these converters would be almost the same:

```
    public DTO_A convertTo(String source, DTO_A destination) {
        return GSON.fromJson(source, DTO_A.class);
    }
```

and 

```
    public DTO_B convertTo(String source, DTO_B destination) {
        return GSON.fromJson(source, DTO_B.class);
    }
```

Since we have *lots* of these types, there is a lot of code duplication. 

Is there a way to pass the actual destination class/type at runtime? 

Something along the lines of CONVERTER.convertTo(String s, Class<DTO_A> clazz)?  But dozer would receive the actual class to map to at runtime, this way we could have a single converter for this generic cases.

**Comment by grubeninspekteur** [comment]
If you implement the `CustomConverter` interface directly instead of inheriting `DozerConverter`, you can access the source and destination classes. You still have to register the converter per JSON/DTO pair in the mapping configuration.

https://dozermapper.github.io/gitbook/documentation/customconverter.html
