### ISSUE TITLE
Dozer 6.5.2 not compatible with Java17 and Jakarta

### ISSUE THREAD

**Issue by sushilpanda** [DozerMapper/dozer#856]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.5.2
* OS version: Windows 
* JDK version: Java17
  
## Whats the problem?
_Steps to reproduce:_
1. Using JAVA17
2. Create a Builder and try mapping from one object to another.
3. We get exception, as Dozer 6.5.2 is not compatible with Jakarta. It still uses javax. package
  
### Observed Results:
We get exceptions, 
Exception No - 1

java.lang.NoClassDefFoundError: javax/el/ExpressionFactory
Throwable:
	at com.github.dozermapper.core.el.ELExpressionFactory.newInstance(ELExpressionFactory.java:120)
	at com.github.dozermapper.core.el.ELExpressionFactory.resolveViaClassLoaderOrTCCL(ELExpressionFactory.java:104)
	at com.github.dozermapper.core.el.ELExpressionFactory.newInstance(ELExpressionFactory.java:80)
	at com.github.dozermapper.core.el.ELExpressionFactory.isSupported(ELExpressionFactory.java:56)
	at com.github.dozermapper.core.el.ELExpressionFactory.isSupported(ELExpressionFactory.java:44)
	at com.github.dozermapper.core.DozerBeanMapperBuilder.getELEngine(DozerBeanMapperBuilder.java:711)
	at com.github.dozermapper.core.DozerBeanMapperBuilder.build(DozerBeanMapperBuilder.java:556)

Exception No- 2
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.github.dozermapper.core.builder.xml.BeanMappingXMLBuilder.<init>(BeanMappingXMLBuilder.java:58)
	at com.github.dozermapper.core.DozerBeanMapperBuilder.buildXmlMappings(DozerBeanMapperBuilder.java:627)
	at com.github.dozermapper.core.DozerBeanMapperBuilder.build(DozerBeanMapperBuilder.java:576)

  
### Expected Results:
We have jakarta.el classes in the classpath but Dozer requires javax.el

## Link to GitHub repo with Unit test
https://github.com/sushilpanda/DozerJava17Test.git
https://github.com/sushilpanda/DozerJava17Test

**Comment by garethahealy** [comment]
java17 is tested against so not surprised and the project isn't active. So if you want to upgrade the deps to java17 and test, that's fine. but you'll need to do the work.

**Comment by sushilpanda** [comment]
> java17 is not tested against so not surprised and the project isn't active. So if you want to upgrade the deps to java17 and test, that's fine. but you'll need to do the work.
> 
> * https://github.com/DozerMapper/dozer/blob/master/.github/workflows/build.yml#L22

hi @garethahealy ,

The dozer project is not active? 
yes I tested with java 17 and since in java 17 "javax" libraries are replaced with "jakarta", I am getting the issues.
Sorry could you please explain what do you mean by you'll need to work?

**Comment by garethahealy** [comment]
- https://github.com/DozerMapper/dozer#project-activity

**Comment by imaxun** [comment]
Don't you already have no plans to maintain?

**Comment by eivinhb** [comment]
Changing Dozer is not on the list for us, right now. Vi use dozer to upgrade and downgrade versions of objects in the api. I have enough on the plate with jakarta upgrades as it is...

I workaround exists! At least for us.

When dozer reads the xml-mapping files it uses Jaxb as default. But it has functionality to use w3c. 
Use vm option:
`-Ddozer.xml.use-jaxb-mapping-engine=false`
This can also be placed in a `dozer.properties` on classpath which is what I did.

But this is not enough to actually map objects. Because there is a check for `javax.xml.bind.JAXBElement.class` hardcoded in the source code here:
https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/MappingProcessor.java#L258

`javax.xml.bind.JAXBElement` is a class that never again should return to our source code, at least. So I just created a dummy-class for now so that the class exists. We never use Dozer to map back to xml anyways. This bypasses the check and dozer is now working for us again.
